# Not for the data science only: Generate matrices together with Numpy

In [1]:
import numpy as np

## 1. Sequences

In [2]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [3]:
arr.shape

(6,)

In [4]:
arr.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr[:, np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [6]:
arr[:, np.newaxis].shape

(6, 1)

In [7]:
np.arange(start = 1,stop = 12, step = 2).reshape(2, 3)

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [8]:
np.arange(1, 12, 2).reshape(2, 3)

array([[ 1,  3,  5],
       [ 7,  9, 11]])

# 2. Random

In [9]:
np.random.random([3,3])

array([[0.51128779, 0.08166971, 0.45970519],
       [0.53899307, 0.17713748, 0.71193327],
       [0.1379933 , 0.23111841, 0.71428433]])

In [10]:
np.random.randn(3, 3)

array([[-0.3354308 , -0.0521325 ,  0.3068469 ],
       [-0.83287716,  0.3106918 , -0.92112837],
       [ 0.49129817,  0.18577052,  1.78254664]])

In [11]:
np.random.randint(0, 3, size=(3, 3))

array([[1, 1, 2],
       [2, 1, 1],
       [0, 1, 1]])

# 3. Distributions

In [12]:
np.linspace(1, 10, 9).reshape(3,3)

array([[ 1.   ,  2.125,  3.25 ],
       [ 4.375,  5.5  ,  6.625],
       [ 7.75 ,  8.875, 10.   ]])

In [13]:
np.logspace(1, 10, 9).reshape(3,3)

array([[1.00000000e+01, 1.33352143e+02, 1.77827941e+03],
       [2.37137371e+04, 3.16227766e+05, 4.21696503e+06],
       [5.62341325e+07, 7.49894209e+08, 1.00000000e+10]])

In [14]:
np.geomspace(1, 10, 9).reshape(3,3)

array([[ 1.        ,  1.33352143,  1.77827941],
       [ 2.37137371,  3.16227766,  4.21696503],
       [ 5.62341325,  7.49894209, 10.        ]])

# 4. Array replication

In [15]:
repl_arr = np.array([1,2,3])

In [16]:
np.tile(repl_arr, [3,1])

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [17]:
np.tile(repl_arr, [2,2])

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

# 5. Diagonal matrix

In [18]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [19]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.eye(3, 4, 0)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [21]:
np.eye(4, 3, 1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

# 6. np.zeros()

In [22]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# 7. np.ones()

In [23]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# 8. np.full()

In [24]:
np.full((3,3), 2, dtype=int)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

# 9. Triangle matrices

In [25]:
np.tri(4, 4)

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [27]:
np.tril(np.arange(1,10).reshape(3,3))

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [28]:
np.triu(np.arange(1,10).reshape(3,3))

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

# Completly custom matrix

In [29]:
np.fromfunction(lambda i, j: i + j, (2, 3), dtype=int)

array([[0, 1, 2],
       [1, 2, 3]])